# Generated by Django 6.0.6 on 2026-07-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_verification_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
