# Generated by Django 6.0.6 on 2026-07-09 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='notifications_last_viewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='DismissedNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(max_length=20)),
                ('reference_id', models.PositiveIntegerField()),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismissed_notifications', to='accounts.businessprofile')),
            ],
            options={
                'unique_together': {('business', 'notif_type', 'reference_id')},
            },
        ),
    ]
