# Generated by Django 6.0.6 on 2026-07-27 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_businessprofile_notifications_last_viewed_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SellerProfile',
        ),
    ]
