# Generated by Django 6.0.6 on 2026-07-27 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_sellerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('business_owner', 'Business Owner')], default='business_owner', max_length=20),
        ),
    ]
