# Generated by Django 6.0.6 on 2026-08-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='plan',
            field=models.CharField(choices=[('free', 'Free Plan'), ('starter', 'Starter'), ('pro', 'Pro Seller'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='unlimited_access',
            field=models.BooleanField(default=False),
        ),
    ]
