# Generated by Django 6.0.6 on 2026-07-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='connection_status',
            field=models.CharField(default='not_connected', max_length=20),
        ),
        migrations.AddField(
            model_name='channel',
            name='last_sync_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='last_sync_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
