# Generated by Django 6.0.6 on 2026-07-13 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_integration', '0002_channel_connection_status_channel_last_sync_attempt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='platform_type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('flipkart', 'Flipkart'), ('other', 'Other')], max_length=20),
        ),
    ]
