# Generated by Django 6.0.6 on 2026-07-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_integration', '0004_synclog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='platform_type',
            field=models.CharField(choices=[('facebook', 'Facebook'), ('instagram', 'Instagram'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('flipkart', 'Flipkart'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=20),
        ),
    ]
