# Generated by Django 6.0.6 on 2026-07-20 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_integration', '0005_alter_channel_platform_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(blank=True, max_length=50)),
                ('raw_payload', models.JSONField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_logs', to='channels_integration.channel')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
