# Generated by Django 6.0.6 on 2026-07-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_integration', '0006_webhooklog'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='remind_later_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='channel',
            name='sync_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='channel',
            name='connection_status',
            field=models.CharField(choices=[('not_connected', 'Not Connected'), ('active', 'Active'), ('expired', 'Expired'), ('syncing', 'Syncing'), ('error', 'Error')], default='not_connected', max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='platform_type',
            field=models.CharField(choices=[('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('youtube', 'YouTube'), ('flipkart', 'Flipkart'), ('whatsapp', 'WhatsApp'), ('other', 'Other')], max_length=20),
        ),
    ]
