# Generated by Django 6.0.6 on 2026-07-27 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_integration', '0007_channel_remind_later_until_channel_sync_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='connection_status',
            field=models.CharField(choices=[('not_connected', 'Not Connected'), ('connected', 'Connected'), ('expired', 'Expired'), ('syncing', 'Syncing'), ('error', 'Error')], default='not_connected', max_length=20),
        ),
    ]
