# Generated by Django 6.0.6 on 2026-07-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_integration', '0008_alter_channel_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='synclog',
            name='error_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
