# Generated by Django 6.0.6 on 2026-07-29 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_integration', '0009_synclog_error_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='synclog',
            name='action',
            field=models.CharField(choices=[('product_sync', 'Product Sync'), ('order_import', 'Order Import'), ('order_notification', 'Order Notification')], max_length=20),
        ),
    ]
