# Generated by Django 6.0.6 on 2026-07-11 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channels_integration', '0001_initial'),
        ('orders', '0002_discount'),
        ('products', '0002_category_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='applicable_categories',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='products.category'),
        ),
        migrations.AddField(
            model_name='discount',
            name='applicable_channels',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='channels_integration.channel'),
        ),
        migrations.AddField(
            model_name='discount',
            name='applicable_products',
            field=models.ManyToManyField(blank=True, related_name='discounts', to='products.product'),
        ),
    ]
