# Generated by Django 6.0.6 on 2026-07-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='external_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
